# Generated by Django 3.2.7 on 2021-10-05 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0004_auto_20211003_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinstance',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='carlisting.car'),
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'On loan'), ('r', 'Reserved'), ('m', 'Maintenance')], default='a', help_text='Car Availability', max_length=1),
        ),
    ]
